name: um_library
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  get_storage: ^2.1.1
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  intl: ^0.19.0
  simple_barcode_scanner: ^0.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/

  uses-material-design: true
